# Default values for Radarr.

image:
  repository: hotio/radarr
  pullPolicy: Always
  tag: nightly

strategy:
  type: Recreate

service:
  main:
    ports:
      main:
        port: 7878

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
